#!/usr/bin/env bash

set -euo pipefail
set -x

version_arg="$1"

git diff --quiet || (echo 'Dirty worktree' && exit 1)
yarn test
yarn version "$version_arg"
version="v$(jq -r .version package.json)"
git add package.json .yarn/versions
git commit -m "$version"
git tag "$version"
yarn build
cp dist/ylis-suodatin.user.js dist/ylis-suodatin.meta.js gh-pages/

cd gh-pages
git add ylis-suodatin.user.js ylis-suodatin.meta.js
git commit -C "$version"
git push origin gh-pages
cd ../

git push origin master --tags
